}POST http://{{host}}:8080/metrics/spd
Content-Type: application/json

{
  "protectedAttribute": "gender",
  "favorableOutcome": 1,
  "outcomeName": "income",
  "privilegedAttribute": 1,
  "unprivilegedAttribute": 0
}
###
POST http://{{host}}:8080/metrics/spd/schedule
Content-Type: application/json

{
  "protectedAttribute": "gender",
  "favorableOutcome": 1,
  "outcomeName": "income",
  "privilegedAttribute": 1,
  "unprivilegedAttribute": 0
}
###
POST http://{{host}}:8080/metrics/spd/unschedule
Content-Type: application/json

{
  "requestId": "287f100e-7c83-454a-ab98-3d4941c6d716"
}
###
###
POST http://{{host}}:8080/metrics/dir/schedule
Content-Type: application/json

{
  "protectedAttribute": "gender",
  "favorableOutcome": 1,
  "outcomeName": "income",
  "privilegedAttribute": 1,
  "unprivilegedAttribute": 0
}
###
POST http://{{host}}:8080/metrics/dir/unschedule
Content-Type: application/json

{
  "requestId": "287f100e-7c83-454a-ab98-3d4941c6d716"
}
###
POST http://{{host}}:8080/metrics/dir
Content-Type: application/json

{
  "protectedAttribute": "gender",
  "favorableOutcome": 1,
  "outcomeName": "income",
  "privilegedAttribute": 1,
  "unprivilegedAttribute": 0
}

###
GET http://{{host}}:8080/q/openapi

###
GET http://{{host}}:8080/metrics/spd/metrics/spd/prometheus

###
GET http://{{host}}:8080/q/metrics